version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: grepwise-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xms512m -Xmx1024m
    volumes:
      - ./logs:/app/logs
      - ./lucene-index:/app/lucene-index
      - backend-data:/app/data
    networks:
      - grepwise-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: grepwise-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - grepwise-network
    # Custom Nginx configuration to proxy API requests to backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  grepwise-network:
    driver: bridge

volumes:
  backend-data:
    driver: local