apiVersion: apps/v1
kind: Deployment
metadata:
  name: grepwise-backend
  namespace: grepwise
  labels:
    app: grepwise
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grepwise
      component: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: grepwise
        component: backend
    spec:
      containers:
      - name: backend
        image: grepwise-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
        - name: JAVA_OPTS
          value: "-Xms512m -Xmx1024m"
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "2Gi"
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        - name: lucene-index
          mountPath: /app/lucene-index
        - name: backend-data
          mountPath: /app/data
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: logs-pvc
      - name: lucene-index
        persistentVolumeClaim:
          claimName: lucene-index-pvc
      - name: backend-data
        persistentVolumeClaim:
          claimName: backend-data-pvc