name: GrepWise CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - uses: graalvm/setup-graalvm@v1
      with:
        version: 'latest'
        java-version: 25
        github-token: ${{ secrets.GITHUB_TOKEN }}
        distribution: 'graalvm-community'
        native-image-job-reports: 'true'
    
    - name: Build and Test with Maven
      run: mvn -ntp clean verify
      continue-on-error: true
      
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: always()
      with:
        report_paths: '**/target/surefire-reports/TEST-*.xml'
        fail_on_failure: false
        require_tests: false
        check_name: Backend Test Results

  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install Dependencies
      run: cd frontend && npm ci
    
    - name: Run Tests
      run: cd frontend && npm run test:coverage
      
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: frontend-coverage
        path: frontend/coverage/
        retention-days: 5

  build-jar:
    name: Build JAR (Boot)
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests]
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: 25
          github-token: ${{ secrets.GITHUB_TOKEN }}
          distribution: 'graalvm-community'
          native-image-job-reports: 'true'
      - name: Build Boot JAR
        run: mvn -ntp -DskipTests package
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: grepwise-jar
          path: |
            target/*-SNAPSHOT.jar
            target/*-SNAPSHOT-plain.jar
          retention-days: 7

  native-build:
    name: Native Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    needs: [backend-tests]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: 25
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Build native
        run: mvn -ntp -Pnative -DskipTests package
      - name: Show target contents
        if: always()
        run: |
          ls -la target || dir target
      - name: Upload Native Artifact
        uses: actions/upload-artifact@v4
        with:
          name: grepwise-native-${{ runner.os }}
          path: |
            target/grepwise
            target/grepwise.exe
            target/*-SNAPSHOT
            target/*-SNAPSHOT.exe
          if-no-files-found: warn
          retention-days: 7

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [build-jar, native-build]
    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: grepwise-jar
          path: dist
      - name: Download Linux native artifact
        uses: actions/download-artifact@v4
        with:
          name: grepwise-native-Linux
          path: dist
      - name: Download macOS native artifact
        uses: actions/download-artifact@v4
        with:
          name: grepwise-native-macOS
          path: dist
      - name: Download Windows native artifact
        uses: actions/download-artifact@v4
        with:
          name: grepwise-native-Windows
          path: dist
      - name: List release assets
        run: ls -la dist
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}